### ISSUE TITLE
Other View Link not Showing

### ISSUE THREAD

**Issue by iamB0rgy** [acadea/fullsite-search#6]
Hi, 

I have customed another link but it is not working. It is returning only the first instance. Rest are returning as default.

`private function resolveModelViewLink(Model $model)
    {
        // Here we list down all the alternative model-link mappings
        // if we dont have a record here, will default to /{model-name}/{model_id}
        $mapping = [
            Recipe::class => 'recipe/{recipe_number}',
            User::class => 'users/{username}',
        ];

        // getting the Fully Qualified Class Name of model
        $modelClass = get_class($model);

        // converting model name to kebab case
        $modelName = Str::plural(Arr::last(explode('\\', $modelClass)));
        $modelName = Str::kebab(Str::camel($modelName));

        // attempt to get from $mapping. We assume every entry has an `{id}` for us to replace
        if(Arr::has($mapping, $modelClass)){
            return str_replace('{recipe_number}', $model->recipe_number, $mapping[$modelClass]);
            return str_replace('{username}', $model->username, $mapping[$modelClass]);
        }
        // assume /{model-name}/{model_id}
        return URL::to('/' . strtolower($modelName) . '/' . $model->recipe_number);
        return URL::to('/' . strtolower($modelName) . '/' . $model->username);
    } `

**Comment by sam-ngu** [comment]
This question is not related to the package. Please refrain from asking questions about your personal project here.

**Comment by iamB0rgy** [comment]
Please remove this piece of sh*t on Github. People are wasting their time using this and in the end, it is completely useless.
